### PR TITLE
Fix support for nullability in Kotlin interfaces and abstract classes

### LINKED ISSUE #708: An Interface With Optional Properties (In Kotlin) Is Generated With Required Properties
Hi, i'm trying to generate from a Kotlin interface like:
`interface ISomeInterface {
   val someProp: String?;
}`
and i get
`interface ISomeInterface {
   someProp: string
}`
i expect "someProp" to be optional: `someProp?: string`

this is the config i have:
` <nullabilityDefinition>undefinedInlineUnion</nullabilityDefinition> `
if i add ` <optionalProperties>useLibraryDefinition</optionalProperties>` then all props are mapped as optional, even if they are not.

 it works well only with classes, but not with interfaces.

Thanks!

### PR DESCRIPTION
**Pull request by mwalser**
When encountering a Kotlin property the type parser attempts to find the backing java field:
https://github.com/vojtechhabarta/typescript-generator/blob/7a33aa0d8b4ce9e0a7d6626e65195b4c995b2871/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/TypeParser.java#L193

However, in interfaces and abstract classes a property might not have a Java field. In this case the parser falls back to the Java type parser which doesn't know about Kotlin nullability:
https://github.com/vojtechhabarta/typescript-generator/blob/7a33aa0d8b4ce9e0a7d6626e65195b4c995b2871/typescript-generator-core/src/main/java/cz/habarta/typescript/generator/parser/TypeParser.java#L200

This PR fixes #708 by changing the behavior to directly use the return type of the Kotlin property.

### CODE REVIEW

File: typescript-generator-core/src/test/java/cz/habarta/typescript/generator/KotlinTest.kt [hunk 1]
```diff
@@ -21,25 +21,102 @@ class KotlinTest {
...
+                        "    nullableArrayFromInterface?: (string | undefined)[];\n" +
+                        "    nullableBooleanFromInterface?: boolean;\n" +
+                        "    nullableFlagFromInterface?: boolean;\n" +
+                        "    nullableGenericArrayFromInterface?: (T | undefined)[];\n" +
+                        "    nullableGenericTypeFromInterface?: T;\n" +
+                        "    nullableListFromInterface?: (string | undefined)[];\n" +
+                        "    nullableStringFromInterface?: string;\n" +
+                        "    testFromInterface: string;\n" +
+                        "    testNullableFromInterface?: string;\n" +
                         "}"
```
Comment (hho) [inline typescript-generator-core/src/test/java/cz/habarta/typescript/generator/KotlinTest.kt:83]: As this is a Kotlin file, I'd use a raw string instead of the concatenation:
```suggestion
                """
                class Abstract<T> {
                    dataFromAbstract?: T;
                    nonNullableBooleanFromAbstract: boolean;
                    nonNullableFlagFromAbstract: boolean;
                    nonNullableStringFromAbstract: string;
                    nullableArrayFromAbstract?: (string | undefined)[];
                    nullableBooleanFromAbstract?: boolean;
                    nullableFlagFromAbstract?: boolean;
                    nullableGenericArrayFromAbstract?: (T | undefined)[];
                    nullableGenericTypeFromAbstract?: T;
                    nullableListFromAbstract?: (string | undefined)[];
                    nullableStringFromAbstract?: string;
                    testFromAbstract: string;
                    testNullableFromAbstract?: string;
                }
                
                class A<T> extends Abstract<T> implements Interface<T> {
                    data?: T;
                    dataFromInterface?: T;
                    nonNullableBoolean: boolean;
                    nonNullableBooleanFromInterface: boolean;
                    nonNullableFlag: boolean;
                    nonNullableFlagFromInterface: boolean;
                    nonNullableString: string;
                    nonNullableStringFromInterface: string;
                    nullableArray?: (string | undefined)[];
                    nullableArrayFromInterface?: (string | undefined)[];
                    nullableBoolean?: boolean;
                    nullableBooleanFromInterface?: boolean;
                    nullableFlag?: boolean;
                    nullableFlagFromInterface?: boolean;
                    nullableGenericArray?: (T | undefined)[];
                    nullableGenericArrayFromInterface?: (T | undefined)[];
                    nullableGenericType?: T;
                    nullableGenericTypeFromInterface?: T;
                    nullableList?: (string | undefined)[];
                    nullableListFromInterface?: (string | undefined)[];
                    nullableString?: string;
                    nullableStringFromInterface?: string;
                    test: string;
                    testFromInterface: string;
                    testNullable?: string;
                    testNullableFromInterface?: string;
                }
                
                interface Interface<T> {
                    dataFromInterface?: T;
                    nonNullableBooleanFromInterface: boolean;
                    nonNullableFlagFromInterface: boolean;
                    nonNullableStringFromInterface: string;
                    nullableArrayFromInterface?: (string | undefined)[];
                    nullableBooleanFromInterface?: boolean;
                    nullableFlagFromInterface?: boolean;
                    nullableGenericArrayFromInterface?: (T | undefined)[];
                    nullableGenericTypeFromInterface?: T;
                    nullableListFromInterface?: (string | undefined)[];
                    nullableStringFromInterface?: string;
                    testFromInterface: string;
                    testNullableFromInterface?: string;
                }""".trimIndent()
```

**Comment by johnellinwood** [comment]
Any idea when this will get merged?

**Comment by yuuzer** [comment]
Hello, Our team are waiting for this fix as well.

**Comment by wojtre** [comment]
Our team is also waiting for this fix, would be cool to merge it.

**Comment by mwalser** [comment]
@vojtechhabarta Is there anything I can do to support this PR getting merged?

If you have any suggestions about changes I have to make to get this in a mergeable state I would gladly invest some time.

**Comment by vojtechhabarta** [comment]
@mwalser, @hho thank you for this PR.
